services:
  qrcode_api:
    image: "${DOCKER_IMAGE}"
    container_name: qrcode_api
    env_file:
      - .env
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode_api.rule=Host(`qrcode-api.elpulpo.xyz`)"
      - "traefik.http.routers.qrcode_api.entrypoints=websecure"
      - "traefik.http.routers.qrcode_api.tls=true"
      - "traefik.http.routers.qrcode_api.tls.certresolver=letencrypt"
      - "traefik.http.services.qrcode_api.loadbalancer.server.port=8000"
    expose:
      - "8000"
    volumes:
      - qrcode_api_data:/data

networks:
  proxy:
    external: true

volumes:
  qrcode_api_data: